language: php

php:
  - 5.5

before_script:
  - composer self-update
  - composer install --dev --prefer-source --no-interaction

script:
  - vendor/bin/phpspec run
  - vendor/bin/behat -f progress

after_success:
  - composer install --no-dev --prefer-source --no-interaction
  - gem install dandelion
  - dandelion deploy

notifications:
  email:
    recipients:
      - tolilybelle@gmail.com
    on_success: change
    on_failure: always